#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanDoChoiLEGO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CNPM_NHOM_1")]
	public partial class CNPM_DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNT(ACCOUNT instance);
    partial void UpdateACCOUNT(ACCOUNT instance);
    partial void DeleteACCOUNT(ACCOUNT instance);
    partial void InsertAGE_RANGE(AGE_RANGE instance);
    partial void UpdateAGE_RANGE(AGE_RANGE instance);
    partial void DeleteAGE_RANGE(AGE_RANGE instance);
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    partial void InsertPRODUCT(PRODUCT instance);
    partial void UpdatePRODUCT(PRODUCT instance);
    partial void DeletePRODUCT(PRODUCT instance);
    partial void InsertPRODUCT_TYPE(PRODUCT_TYPE instance);
    partial void UpdatePRODUCT_TYPE(PRODUCT_TYPE instance);
    partial void DeletePRODUCT_TYPE(PRODUCT_TYPE instance);
    partial void InsertPURCHASE_BILL(PURCHASE_BILL instance);
    partial void UpdatePURCHASE_BILL(PURCHASE_BILL instance);
    partial void DeletePURCHASE_BILL(PURCHASE_BILL instance);
    partial void InsertSTAFF(STAFF instance);
    partial void UpdateSTAFF(STAFF instance);
    partial void DeleteSTAFF(STAFF instance);
    #endregion
		
		public CNPM_DataClassesDataContext() : 
				base(global::QuanLyBanDoChoiLEGO.Properties.Settings.Default.CNPM_NHOM_1ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CNPM_DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CNPM_DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CNPM_DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CNPM_DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<STORAGE_HISTORY> STORAGE_HISTORies
		{
			get
			{
				return this.GetTable<STORAGE_HISTORY>();
			}
		}
		
		public System.Data.Linq.Table<AGE_RANGE> AGE_RANGEs
		{
			get
			{
				return this.GetTable<AGE_RANGE>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCT> PRODUCTs
		{
			get
			{
				return this.GetTable<PRODUCT>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCT_TYPE> PRODUCT_TYPEs
		{
			get
			{
				return this.GetTable<PRODUCT_TYPE>();
			}
		}
		
		public System.Data.Linq.Table<PURCHASE_BILL> PURCHASE_BILLs
		{
			get
			{
				return this.GetTable<PURCHASE_BILL>();
			}
		}
		
		public System.Data.Linq.Table<PURCHASE_BILL_DETAIL> PURCHASE_BILL_DETAILs
		{
			get
			{
				return this.GetTable<PURCHASE_BILL_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<STAFF> STAFFs
		{
			get
			{
				return this.GetTable<STAFF>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_staff;
		
		private string _username;
		
		private string _pass;
		
		private System.Nullable<byte> _is_admin;
		
		private EntityRef<STAFF> _STAFF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_staffChanging(System.Nullable<int> value);
    partial void Onid_staffChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void Onis_adminChanging(System.Nullable<byte> value);
    partial void Onis_adminChanged();
    #endregion
		
		public ACCOUNT()
		{
			this._STAFF = default(EntityRef<STAFF>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_staff", DbType="Int")]
		public System.Nullable<int> id_staff
		{
			get
			{
				return this._id_staff;
			}
			set
			{
				if ((this._id_staff != value))
				{
					if (this._STAFF.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_staffChanging(value);
					this.SendPropertyChanging();
					this._id_staff = value;
					this.SendPropertyChanged("id_staff");
					this.Onid_staffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(20)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_admin", DbType="TinyInt")]
		public System.Nullable<byte> is_admin
		{
			get
			{
				return this._is_admin;
			}
			set
			{
				if ((this._is_admin != value))
				{
					this.Onis_adminChanging(value);
					this.SendPropertyChanging();
					this._is_admin = value;
					this.SendPropertyChanged("is_admin");
					this.Onis_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STAFF_ACCOUNT", Storage="_STAFF", ThisKey="id_staff", OtherKey="id", IsForeignKey=true)]
		public STAFF STAFF
		{
			get
			{
				return this._STAFF.Entity;
			}
			set
			{
				STAFF previousValue = this._STAFF.Entity;
				if (((previousValue != value) 
							|| (this._STAFF.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STAFF.Entity = null;
						previousValue.ACCOUNTs.Remove(this);
					}
					this._STAFF.Entity = value;
					if ((value != null))
					{
						value.ACCOUNTs.Add(this);
						this._id_staff = value.id;
					}
					else
					{
						this._id_staff = default(Nullable<int>);
					}
					this.SendPropertyChanged("STAFF");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STORAGE_HISTORY")]
	public partial class STORAGE_HISTORY
	{
		
		private int _id_product;
		
		private System.Nullable<System.DateTime> _input_date;
		
		private System.Nullable<int> _quantity;
		
		public STORAGE_HISTORY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_product", DbType="Int NOT NULL")]
		public int id_product
		{
			get
			{
				return this._id_product;
			}
			set
			{
				if ((this._id_product != value))
				{
					this._id_product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_input_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> input_date
		{
			get
			{
				return this._input_date;
			}
			set
			{
				if ((this._input_date != value))
				{
					this._input_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AGE_RANGE")]
	public partial class AGE_RANGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _id;
		
		private string _age_range_name;
		
		private EntitySet<PRODUCT> _PRODUCTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(byte value);
    partial void OnidChanged();
    partial void Onage_range_nameChanging(string value);
    partial void Onage_range_nameChanged();
    #endregion
		
		public AGE_RANGE()
		{
			this._PRODUCTs = new EntitySet<PRODUCT>(new Action<PRODUCT>(this.attach_PRODUCTs), new Action<PRODUCT>(this.detach_PRODUCTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age_range_name", DbType="NVarChar(50)")]
		public string age_range_name
		{
			get
			{
				return this._age_range_name;
			}
			set
			{
				if ((this._age_range_name != value))
				{
					this.Onage_range_nameChanging(value);
					this.SendPropertyChanging();
					this._age_range_name = value;
					this.SendPropertyChanged("age_range_name");
					this.Onage_range_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AGE_RANGE_PRODUCT", Storage="_PRODUCTs", ThisKey="id", OtherKey="id_age_range")]
		public EntitySet<PRODUCT> PRODUCTs
		{
			get
			{
				return this._PRODUCTs;
			}
			set
			{
				this._PRODUCTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTs(PRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.AGE_RANGE = this;
		}
		
		private void detach_PRODUCTs(PRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.AGE_RANGE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _customer_name;
		
		private string _phone_number;
		
		private System.Nullable<System.DateTime> _date_of_birth;
		
		private string _home_address;
		
		private EntitySet<PURCHASE_BILL> _PURCHASE_BILLs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncustomer_nameChanging(string value);
    partial void Oncustomer_nameChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    partial void Onhome_addressChanging(string value);
    partial void Onhome_addressChanged();
    #endregion
		
		public CUSTOMER()
		{
			this._PURCHASE_BILLs = new EntitySet<PURCHASE_BILL>(new Action<PURCHASE_BILL>(this.attach_PURCHASE_BILLs), new Action<PURCHASE_BILL>(this.detach_PURCHASE_BILLs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_name", DbType="NVarChar(50)")]
		public string customer_name
		{
			get
			{
				return this._customer_name;
			}
			set
			{
				if ((this._customer_name != value))
				{
					this.Oncustomer_nameChanging(value);
					this.SendPropertyChanging();
					this._customer_name = value;
					this.SendPropertyChanged("customer_name");
					this.Oncustomer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(12)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_birth
		{
			get
			{
				return this._date_of_birth;
			}
			set
			{
				if ((this._date_of_birth != value))
				{
					this.Ondate_of_birthChanging(value);
					this.SendPropertyChanging();
					this._date_of_birth = value;
					this.SendPropertyChanged("date_of_birth");
					this.Ondate_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_address", DbType="NVarChar(100)")]
		public string home_address
		{
			get
			{
				return this._home_address;
			}
			set
			{
				if ((this._home_address != value))
				{
					this.Onhome_addressChanging(value);
					this.SendPropertyChanging();
					this._home_address = value;
					this.SendPropertyChanged("home_address");
					this.Onhome_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_PURCHASE_BILL", Storage="_PURCHASE_BILLs", ThisKey="id", OtherKey="id_customer")]
		public EntitySet<PURCHASE_BILL> PURCHASE_BILLs
		{
			get
			{
				return this._PURCHASE_BILLs;
			}
			set
			{
				this._PURCHASE_BILLs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PURCHASE_BILLs(PURCHASE_BILL entity)
		{
			this.SendPropertyChanging();
			entity.CUSTOMER = this;
		}
		
		private void detach_PURCHASE_BILLs(PURCHASE_BILL entity)
		{
			this.SendPropertyChanging();
			entity.CUSTOMER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCT")]
	public partial class PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<byte> _id_type;
		
		private System.Nullable<byte> _gender;
		
		private System.Nullable<byte> _id_age_range;
		
		private string _product_name;
		
		private System.Nullable<double> _price;
		
		private System.Nullable<int> _quantity;
		
		private string _img_path;
		
		private string _product_desc;
		
		private EntityRef<AGE_RANGE> _AGE_RANGE;
		
		private EntityRef<PRODUCT_TYPE> _PRODUCT_TYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_typeChanging(System.Nullable<byte> value);
    partial void Onid_typeChanged();
    partial void OngenderChanging(System.Nullable<byte> value);
    partial void OngenderChanged();
    partial void Onid_age_rangeChanging(System.Nullable<byte> value);
    partial void Onid_age_rangeChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void OnpriceChanging(System.Nullable<double> value);
    partial void OnpriceChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void Onimg_pathChanging(string value);
    partial void Onimg_pathChanged();
    partial void Onproduct_descChanging(string value);
    partial void Onproduct_descChanged();
    #endregion
		
		public PRODUCT()
		{
			this._AGE_RANGE = default(EntityRef<AGE_RANGE>);
			this._PRODUCT_TYPE = default(EntityRef<PRODUCT_TYPE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_type", DbType="TinyInt")]
		public System.Nullable<byte> id_type
		{
			get
			{
				return this._id_type;
			}
			set
			{
				if ((this._id_type != value))
				{
					if (this._PRODUCT_TYPE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_typeChanging(value);
					this.SendPropertyChanging();
					this._id_type = value;
					this.SendPropertyChanged("id_type");
					this.Onid_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="TinyInt")]
		public System.Nullable<byte> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_age_range", DbType="TinyInt")]
		public System.Nullable<byte> id_age_range
		{
			get
			{
				return this._id_age_range;
			}
			set
			{
				if ((this._id_age_range != value))
				{
					if (this._AGE_RANGE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_age_rangeChanging(value);
					this.SendPropertyChanging();
					this._id_age_range = value;
					this.SendPropertyChanged("id_age_range");
					this.Onid_age_rangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(50)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img_path", DbType="VarChar(100)")]
		public string img_path
		{
			get
			{
				return this._img_path;
			}
			set
			{
				if ((this._img_path != value))
				{
					this.Onimg_pathChanging(value);
					this.SendPropertyChanging();
					this._img_path = value;
					this.SendPropertyChanged("img_path");
					this.Onimg_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_desc", DbType="NVarChar(100)")]
		public string product_desc
		{
			get
			{
				return this._product_desc;
			}
			set
			{
				if ((this._product_desc != value))
				{
					this.Onproduct_descChanging(value);
					this.SendPropertyChanging();
					this._product_desc = value;
					this.SendPropertyChanged("product_desc");
					this.Onproduct_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AGE_RANGE_PRODUCT", Storage="_AGE_RANGE", ThisKey="id_age_range", OtherKey="id", IsForeignKey=true)]
		public AGE_RANGE AGE_RANGE
		{
			get
			{
				return this._AGE_RANGE.Entity;
			}
			set
			{
				AGE_RANGE previousValue = this._AGE_RANGE.Entity;
				if (((previousValue != value) 
							|| (this._AGE_RANGE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AGE_RANGE.Entity = null;
						previousValue.PRODUCTs.Remove(this);
					}
					this._AGE_RANGE.Entity = value;
					if ((value != null))
					{
						value.PRODUCTs.Add(this);
						this._id_age_range = value.id;
					}
					else
					{
						this._id_age_range = default(Nullable<byte>);
					}
					this.SendPropertyChanged("AGE_RANGE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_TYPE_PRODUCT", Storage="_PRODUCT_TYPE", ThisKey="id_type", OtherKey="id", IsForeignKey=true)]
		public PRODUCT_TYPE PRODUCT_TYPE
		{
			get
			{
				return this._PRODUCT_TYPE.Entity;
			}
			set
			{
				PRODUCT_TYPE previousValue = this._PRODUCT_TYPE.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCT_TYPE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCT_TYPE.Entity = null;
						previousValue.PRODUCTs.Remove(this);
					}
					this._PRODUCT_TYPE.Entity = value;
					if ((value != null))
					{
						value.PRODUCTs.Add(this);
						this._id_type = value.id;
					}
					else
					{
						this._id_type = default(Nullable<byte>);
					}
					this.SendPropertyChanged("PRODUCT_TYPE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCT_TYPE")]
	public partial class PRODUCT_TYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _id;
		
		private string _product_type_name;
		
		private string _product_type_desc;
		
		private EntitySet<PRODUCT> _PRODUCTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(byte value);
    partial void OnidChanged();
    partial void Onproduct_type_nameChanging(string value);
    partial void Onproduct_type_nameChanged();
    partial void Onproduct_type_descChanging(string value);
    partial void Onproduct_type_descChanged();
    #endregion
		
		public PRODUCT_TYPE()
		{
			this._PRODUCTs = new EntitySet<PRODUCT>(new Action<PRODUCT>(this.attach_PRODUCTs), new Action<PRODUCT>(this.detach_PRODUCTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_type_name", DbType="NVarChar(50)")]
		public string product_type_name
		{
			get
			{
				return this._product_type_name;
			}
			set
			{
				if ((this._product_type_name != value))
				{
					this.Onproduct_type_nameChanging(value);
					this.SendPropertyChanging();
					this._product_type_name = value;
					this.SendPropertyChanged("product_type_name");
					this.Onproduct_type_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_type_desc", DbType="NVarChar(100)")]
		public string product_type_desc
		{
			get
			{
				return this._product_type_desc;
			}
			set
			{
				if ((this._product_type_desc != value))
				{
					this.Onproduct_type_descChanging(value);
					this.SendPropertyChanging();
					this._product_type_desc = value;
					this.SendPropertyChanged("product_type_desc");
					this.Onproduct_type_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_TYPE_PRODUCT", Storage="_PRODUCTs", ThisKey="id", OtherKey="id_type")]
		public EntitySet<PRODUCT> PRODUCTs
		{
			get
			{
				return this._PRODUCTs;
			}
			set
			{
				this._PRODUCTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTs(PRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCT_TYPE = this;
		}
		
		private void detach_PRODUCTs(PRODUCT entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCT_TYPE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PURCHASE_BILL")]
	public partial class PURCHASE_BILL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_staff;
		
		private System.Nullable<int> _id_customer;
		
		private System.Nullable<System.DateTime> _date_of_purchase;
		
		private string _purchase_bill_desc;
		
		private System.Nullable<double> _total_cost;
		
		private EntityRef<CUSTOMER> _CUSTOMER;
		
		private EntityRef<STAFF> _STAFF;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_staffChanging(System.Nullable<int> value);
    partial void Onid_staffChanged();
    partial void Onid_customerChanging(System.Nullable<int> value);
    partial void Onid_customerChanged();
    partial void Ondate_of_purchaseChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_purchaseChanged();
    partial void Onpurchase_bill_descChanging(string value);
    partial void Onpurchase_bill_descChanged();
    partial void Ontotal_costChanging(System.Nullable<double> value);
    partial void Ontotal_costChanged();
    #endregion
		
		public PURCHASE_BILL()
		{
			this._CUSTOMER = default(EntityRef<CUSTOMER>);
			this._STAFF = default(EntityRef<STAFF>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_staff", DbType="Int")]
		public System.Nullable<int> id_staff
		{
			get
			{
				return this._id_staff;
			}
			set
			{
				if ((this._id_staff != value))
				{
					if (this._STAFF.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_staffChanging(value);
					this.SendPropertyChanging();
					this._id_staff = value;
					this.SendPropertyChanged("id_staff");
					this.Onid_staffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					if (this._CUSTOMER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_purchase", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_of_purchase
		{
			get
			{
				return this._date_of_purchase;
			}
			set
			{
				if ((this._date_of_purchase != value))
				{
					this.Ondate_of_purchaseChanging(value);
					this.SendPropertyChanging();
					this._date_of_purchase = value;
					this.SendPropertyChanged("date_of_purchase");
					this.Ondate_of_purchaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purchase_bill_desc", DbType="NVarChar(100)")]
		public string purchase_bill_desc
		{
			get
			{
				return this._purchase_bill_desc;
			}
			set
			{
				if ((this._purchase_bill_desc != value))
				{
					this.Onpurchase_bill_descChanging(value);
					this.SendPropertyChanging();
					this._purchase_bill_desc = value;
					this.SendPropertyChanged("purchase_bill_desc");
					this.Onpurchase_bill_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_cost", DbType="Float")]
		public System.Nullable<double> total_cost
		{
			get
			{
				return this._total_cost;
			}
			set
			{
				if ((this._total_cost != value))
				{
					this.Ontotal_costChanging(value);
					this.SendPropertyChanging();
					this._total_cost = value;
					this.SendPropertyChanged("total_cost");
					this.Ontotal_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_PURCHASE_BILL", Storage="_CUSTOMER", ThisKey="id_customer", OtherKey="id", IsForeignKey=true)]
		public CUSTOMER CUSTOMER
		{
			get
			{
				return this._CUSTOMER.Entity;
			}
			set
			{
				CUSTOMER previousValue = this._CUSTOMER.Entity;
				if (((previousValue != value) 
							|| (this._CUSTOMER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CUSTOMER.Entity = null;
						previousValue.PURCHASE_BILLs.Remove(this);
					}
					this._CUSTOMER.Entity = value;
					if ((value != null))
					{
						value.PURCHASE_BILLs.Add(this);
						this._id_customer = value.id;
					}
					else
					{
						this._id_customer = default(Nullable<int>);
					}
					this.SendPropertyChanged("CUSTOMER");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STAFF_PURCHASE_BILL", Storage="_STAFF", ThisKey="id_staff", OtherKey="id", IsForeignKey=true)]
		public STAFF STAFF
		{
			get
			{
				return this._STAFF.Entity;
			}
			set
			{
				STAFF previousValue = this._STAFF.Entity;
				if (((previousValue != value) 
							|| (this._STAFF.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STAFF.Entity = null;
						previousValue.PURCHASE_BILLs.Remove(this);
					}
					this._STAFF.Entity = value;
					if ((value != null))
					{
						value.PURCHASE_BILLs.Add(this);
						this._id_staff = value.id;
					}
					else
					{
						this._id_staff = default(Nullable<int>);
					}
					this.SendPropertyChanged("STAFF");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PURCHASE_BILL_DETAIL")]
	public partial class PURCHASE_BILL_DETAIL
	{
		
		private System.Nullable<int> _id_bill;
		
		private int _id_product;
		
		private System.Nullable<double> _cost;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<double> _tt_cost;
		
		public PURCHASE_BILL_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_bill", DbType="Int")]
		public System.Nullable<int> id_bill
		{
			get
			{
				return this._id_bill;
			}
			set
			{
				if ((this._id_bill != value))
				{
					this._id_bill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_product", DbType="Int NOT NULL")]
		public int id_product
		{
			get
			{
				return this._id_product;
			}
			set
			{
				if ((this._id_product != value))
				{
					this._id_product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cost", DbType="Float")]
		public System.Nullable<double> cost
		{
			get
			{
				return this._cost;
			}
			set
			{
				if ((this._cost != value))
				{
					this._cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this._quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tt_cost", DbType="Float")]
		public System.Nullable<double> tt_cost
		{
			get
			{
				return this._tt_cost;
			}
			set
			{
				if ((this._tt_cost != value))
				{
					this._tt_cost = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STAFF")]
	public partial class STAFF : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _staff_name;
		
		private string _phone_number;
		
		private System.Nullable<System.DateTime> _date_of_birth;
		
		private string _home_address;
		
		private string _citizen_id;
		
		private EntitySet<ACCOUNT> _ACCOUNTs;
		
		private EntitySet<PURCHASE_BILL> _PURCHASE_BILLs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstaff_nameChanging(string value);
    partial void Onstaff_nameChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    partial void Onhome_addressChanging(string value);
    partial void Onhome_addressChanged();
    partial void Oncitizen_idChanging(string value);
    partial void Oncitizen_idChanged();
    #endregion
		
		public STAFF()
		{
			this._ACCOUNTs = new EntitySet<ACCOUNT>(new Action<ACCOUNT>(this.attach_ACCOUNTs), new Action<ACCOUNT>(this.detach_ACCOUNTs));
			this._PURCHASE_BILLs = new EntitySet<PURCHASE_BILL>(new Action<PURCHASE_BILL>(this.attach_PURCHASE_BILLs), new Action<PURCHASE_BILL>(this.detach_PURCHASE_BILLs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_name", DbType="NVarChar(50)")]
		public string staff_name
		{
			get
			{
				return this._staff_name;
			}
			set
			{
				if ((this._staff_name != value))
				{
					this.Onstaff_nameChanging(value);
					this.SendPropertyChanging();
					this._staff_name = value;
					this.SendPropertyChanged("staff_name");
					this.Onstaff_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(12)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date")]
		public System.Nullable<System.DateTime> date_of_birth
		{
			get
			{
				return this._date_of_birth;
			}
			set
			{
				if ((this._date_of_birth != value))
				{
					this.Ondate_of_birthChanging(value);
					this.SendPropertyChanging();
					this._date_of_birth = value;
					this.SendPropertyChanged("date_of_birth");
					this.Ondate_of_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_address", DbType="NVarChar(100)")]
		public string home_address
		{
			get
			{
				return this._home_address;
			}
			set
			{
				if ((this._home_address != value))
				{
					this.Onhome_addressChanging(value);
					this.SendPropertyChanging();
					this._home_address = value;
					this.SendPropertyChanged("home_address");
					this.Onhome_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_citizen_id", DbType="VarChar(12)")]
		public string citizen_id
		{
			get
			{
				return this._citizen_id;
			}
			set
			{
				if ((this._citizen_id != value))
				{
					this.Oncitizen_idChanging(value);
					this.SendPropertyChanging();
					this._citizen_id = value;
					this.SendPropertyChanged("citizen_id");
					this.Oncitizen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STAFF_ACCOUNT", Storage="_ACCOUNTs", ThisKey="id", OtherKey="id_staff")]
		public EntitySet<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this._ACCOUNTs;
			}
			set
			{
				this._ACCOUNTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STAFF_PURCHASE_BILL", Storage="_PURCHASE_BILLs", ThisKey="id", OtherKey="id_staff")]
		public EntitySet<PURCHASE_BILL> PURCHASE_BILLs
		{
			get
			{
				return this._PURCHASE_BILLs;
			}
			set
			{
				this._PURCHASE_BILLs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.STAFF = this;
		}
		
		private void detach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.STAFF = null;
		}
		
		private void attach_PURCHASE_BILLs(PURCHASE_BILL entity)
		{
			this.SendPropertyChanging();
			entity.STAFF = this;
		}
		
		private void detach_PURCHASE_BILLs(PURCHASE_BILL entity)
		{
			this.SendPropertyChanging();
			entity.STAFF = null;
		}
	}
}
#pragma warning restore 1591
