<?xml version="1.0" encoding="utf-8"?><Database Name="CNPM_NHOM_1" Class="CNPM_DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-C7M7T04D\SQLEXPRESS;Initial Catalog=CNPM_NHOM_1;Integrated Security=True" SettingsObjectName="QuanLyBanDoChoiLEGO.Properties.Settings" SettingsPropertyName="CNPM_NHOM_1ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCOUNT" Member="ACCOUNTs">
    <Type Name="ACCOUNT">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_staff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="pass" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="is_admin" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="STAFF_ACCOUNT" Member="STAFF" ThisKey="id_staff" OtherKey="id" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STORAGE_HISTORY" Member="STORAGE_HISTORies">
    <Type Name="STORAGE_HISTORY">
      <Column Name="id_product" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="input_date" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PRODUCT_STORAGE_HISTORY" Member="PRODUCT" ThisKey="id_product" OtherKey="id" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AGE_RANGE" Member="AGE_RANGEs">
    <Type Name="AGE_RANGE">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="age_range_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="AGE_RANGE_PRODUCT" Member="PRODUCTs" ThisKey="id" OtherKey="id_age_range" Type="PRODUCT" />
    </Type>
  </Table>
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customer_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="home_address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="CUSTOMER_PURCHASE_BILL" Member="PURCHASE_BILLs" ThisKey="id" OtherKey="id_customer" Type="PURCHASE_BILL" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_type" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="id_age_range" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="img_path" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="product_desc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="PRODUCT_STORAGE_HISTORY" Member="STORAGE_HISTORies" ThisKey="id" OtherKey="id_product" Type="STORAGE_HISTORY" />
      <Association Name="PRODUCT_PURCHASE_BILL_DETAIL" Member="PURCHASE_BILL_DETAILs" ThisKey="id" OtherKey="id_product" Type="PURCHASE_BILL_DETAIL" />
      <Association Name="AGE_RANGE_PRODUCT" Member="AGE_RANGE" ThisKey="id_age_range" OtherKey="id" Type="AGE_RANGE" IsForeignKey="true" />
      <Association Name="PRODUCT_TYPE_PRODUCT" Member="PRODUCT_TYPE" ThisKey="id_type" OtherKey="id" Type="PRODUCT_TYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT_TYPE" Member="PRODUCT_TYPEs">
    <Type Name="PRODUCT_TYPE">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_type_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="product_type_desc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="PRODUCT_TYPE_PRODUCT" Member="PRODUCTs" ThisKey="id" OtherKey="id_type" Type="PRODUCT" />
    </Type>
  </Table>
  <Table Name="dbo.PURCHASE_BILL" Member="PURCHASE_BILLs">
    <Type Name="PURCHASE_BILL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_staff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_of_purchase" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="purchase_bill_desc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="total_cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PURCHASE_BILL_PURCHASE_BILL_DETAIL" Member="PURCHASE_BILL_DETAILs" ThisKey="id" OtherKey="id_bill" Type="PURCHASE_BILL_DETAIL" />
      <Association Name="CUSTOMER_PURCHASE_BILL" Member="CUSTOMER" ThisKey="id_customer" OtherKey="id" Type="CUSTOMER" IsForeignKey="true" />
      <Association Name="STAFF_PURCHASE_BILL" Member="STAFF" ThisKey="id_staff" OtherKey="id" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PURCHASE_BILL_DETAIL" Member="PURCHASE_BILL_DETAILs">
    <Type Name="PURCHASE_BILL_DETAIL">
      <Column Name="id_bill" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_product" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tt_cost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PURCHASE_BILL_PURCHASE_BILL_DETAIL" Member="PURCHASE_BILL" ThisKey="id_bill" OtherKey="id" Type="PURCHASE_BILL" IsForeignKey="true" />
      <Association Name="PRODUCT_PURCHASE_BILL_DETAIL" Member="PRODUCT" ThisKey="id_product" OtherKey="id" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STAFF" Member="STAFFs">
    <Type Name="STAFF">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staff_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="home_address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="citizen_id" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Association Name="STAFF_ACCOUNT" Member="ACCOUNTs" ThisKey="id" OtherKey="id_staff" Type="ACCOUNT" />
      <Association Name="STAFF_PURCHASE_BILL" Member="PURCHASE_BILLs" ThisKey="id" OtherKey="id_staff" Type="PURCHASE_BILL" />
    </Type>
  </Table>
</Database>