//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanDoChoiLEGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.PURCHASE_BILL_DETAIL = new HashSet<PURCHASE_BILL_DETAIL>();
            this.STORAGEs = new HashSet<STORAGE>();
        }
    
        public int id { get; set; }
        public int id_type { get; set; }
        public string product_name { get; set; }
        public string gender { get; set; }
        public string age_range { get; set; }
        public Nullable<double> price { get; set; }
        public string img_path { get; set; }
        public string product_desc { get; set; }
    
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_BILL_DETAIL> PURCHASE_BILL_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORAGE> STORAGEs { get; set; }
    }
}
