//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanDoChoiLEGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public decimal id_type { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> age_range { get; set; }
        public string product_name { get; set; }
        public Nullable<double> price { get; set; }
        public string img_path { get; set; }
        public string product_desc { get; set; }
    
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
    }
}
