//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanDoChoiLEGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE_BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PURCHASE_BILL()
        {
            this.PURCHASE_BILL_DETAIL = new HashSet<PURCHASE_BILL_DETAIL>();
        }
    
        public decimal id { get; set; }
        public decimal id_staff { get; set; }
        public decimal id_customer { get; set; }
        public Nullable<System.DateTime> date_of_purchase { get; set; }
        public string purchase_bill_desc { get; set; }
        public Nullable<double> total_cost { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_BILL_DETAIL> PURCHASE_BILL_DETAIL { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
