//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanDoChoiLEGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORAGE
    {
        public int id_type { get; set; }
        public string product_type_name { get; set; }
        public int id_product { get; set; }
        public string product_name { get; set; }
        public string gender { get; set; }
        public string age_range { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> input_date { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
    }
}
