//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanDoChoiLEGO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORAGE()
        {
            this.PURCHASE_BILL_DETAIL = new HashSet<PURCHASE_BILL_DETAIL>();
        }
    
        public decimal id_type { get; set; }
        public decimal id_product { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> input_date { get; set; }
    
        public virtual PRODUCT_TYPE PRODUCT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_BILL_DETAIL> PURCHASE_BILL_DETAIL { get; set; }
    }
}
